/**
 * PT-BR labels for COCO classes — shared by the renderer (canvas boxes, panel)
 * and the runtime (alert/TTS text) so labels are always shown in Portuguese.
 */

export const PT_CLASS: Record<string, string> = {
  person: 'pessoa',
  bicycle: 'bicicleta',
  car: 'carro',
  motorcycle: 'moto',
  airplane: 'avião',
  bus: 'ônibus',
  train: 'trem',
  truck: 'caminhão',
  boat: 'barco',
  'traffic light': 'semáforo',
  'fire hydrant': 'hidrante',
  'stop sign': 'placa de pare',
  'parking meter': 'parquímetro',
  bench: 'banco',
  bird: 'pássaro',
  cat: 'gato',
  dog: 'cachorro',
  horse: 'cavalo',
  sheep: 'ovelha',
  cow: 'vaca',
  elephant: 'elefante',
  bear: 'urso',
  zebra: 'zebra',
  giraffe: 'girafa',
  backpack: 'mochila',
  umbrella: 'guarda-chuva',
  handbag: 'bolsa',
  tie: 'gravata',
  suitcase: 'mala',
  frisbee: 'frisbee',
  skis: 'esquis',
  snowboard: 'snowboard',
  'sports ball': 'bola',
  kite: 'pipa',
  'baseball bat': 'taco de beisebol',
  'baseball glove': 'luva de beisebol',
  skateboard: 'skate',
  surfboard: 'prancha de surf',
  'tennis racket': 'raquete',
  bottle: 'garrafa',
  'wine glass': 'taça',
  cup: 'copo',
  fork: 'garfo',
  knife: 'faca',
  spoon: 'colher',
  bowl: 'tigela',
  banana: 'banana',
  apple: 'maçã',
  sandwich: 'sanduíche',
  orange: 'laranja',
  broccoli: 'brócolis',
  carrot: 'cenoura',
  'hot dog': 'cachorro-quente',
  pizza: 'pizza',
  donut: 'rosquinha',
  cake: 'bolo',
  chair: 'cadeira',
  couch: 'sofá',
  'potted plant': 'planta',
  bed: 'cama',
  'dining table': 'mesa',
  toilet: 'vaso sanitário',
  tv: 'televisão',
  laptop: 'notebook',
  mouse: 'mouse',
  remote: 'controle',
  keyboard: 'teclado',
  'cell phone': 'celular',
  microwave: 'micro-ondas',
  oven: 'forno',
  toaster: 'torradeira',
  sink: 'pia',
  refrigerator: 'geladeira',
  book: 'livro',
  clock: 'relógio',
  vase: 'vaso',
  scissors: 'tesoura',
  'teddy bear': 'ursinho',
  'hair drier': 'secador',
  toothbrush: 'escova de dentes'
}

export function ptLabel(className?: string): string {
  if (!className) return ''
  return PT_CLASS[className.toLowerCase()] || className
}
